### PR TITLE
use FakeAuth

### PR DESCRIPTION
**Pull request by djmitche**
@jonasfj and @petemoore I'm curious what you think about this.  If you like it, I think it might actually be a better fit for a new `taskcluster-lib-testing`.

The idea is to intercept calls to `authenticateHawk` and return success, with the scopes assigned (locally to the test scripts) to that clientId or temporary credential.  This avoids the need to have production clientIds with finely-tuned scopes, especially when you want to test that certain operations are forbidden (as we do here, and should other places).

Note that this does not do anything to address the calls to other APIs (those need to be mocked out directly either with Nock or via dependency injection, as I did with tc-hooks' calls to queue.createTask), nor to address use of Azure tables.  But it's a start.

### CODE REVIEW

**Comment by jonasfj** [comment]
Hmm... this is an interesting approach... We already have `base.testing.createMockAuthServer`, it also handles both `auth.azureTableSAS` and `auth.authenticateHawk`, see:
https://github.com/taskcluster/taskcluster-lib-testing/blob/106ea245cfa18e477aeecf4d639261a7d2456cfe/src/testing.js#L354-L376

If you need to use azure table you can give it: `azureAccounts` or you can give it tc credentials + `authBaseUrl` which defaults to `auth.taskcluster.net`.

To use `createMockAuthServer` you just give the test profile a special key for the `authBaseUrl`:
https://github.com/taskcluster/taskcluster-queue/blob/da0119e5019042c65d5ad5af35871324e59fccbb/config/test.js#L38
And setup the mockAuthServer in the `mocha.before`:
https://github.com/taskcluster/taskcluster-queue/blob/da0119e5019042c65d5ad5af35871324e59fccbb/test/api/helper.js#L73-L77

I'm not sure how solid nock is, but perhaps we could do something with it... We definitely ought to have less duplication between the `helper.js` files in all the projects.

**Comment by djmitche** [comment]
OK, I moved this in https://github.com/taskcluster/taskcluster-lib-testing/pull/2

**Comment by petemoore** [comment]
302 @jhford :)

**Comment by djmitche** [comment]
I'll use that lib once it lands in taskcluster-lib-testing

**Comment by djmitche** [comment]
OK, @jhford, how's this look?

**Comment by jhford** [comment]
This looks good... i'm confused what the status of fakeauth is.  I thought it was merged into taskcluster-lib-testing.  If that's true, why do we have another copy here?

r+ providing we have a single copy of fakeauth.js in the tree somewhere

**Comment by djmitche** [comment]
There's no copy of fakeauth.js in this patch, as far as I can see..

**Comment by jhford** [comment]
ugh, the github view when I looked at it earlier must have been improperly cached, since it was showing the complete fakeauth.js in the files changed view.  Doing a cache-clear reload fixed it.

**Pull request merged**
