### PR TITLE
Update tc-base in preparation for adding sentry

### PR DESCRIPTION
**Pull request by imbstack**
This required a module bump so a few things had to change with it. I also went ahead and bumped the node version because I figured why not if it works?

**This will require updating heroku env vars before deployment.**

If any of this doesn't make sense, feel free to roundly reject it. I have no emotional attachment to this patch!

### CODE REVIEW

**Comment by djmitche** [comment]
Can you add a `user-config-example.yml`?

Also, will you take care of deploying?  This looks good.

**Comment by imbstack** [comment]
Yep, I'll definitely take care of deploying.

Strangely enough the tests pass without anything in user-config.yml. Should I just have an empty ```user-config-example.yml``` or does that indicate that something is wrong with the tests?

**Comment by djmitche** [comment]
Oh, right, I think I fixed this so it doesn't need creds to pass.  IIRC some of the tests skip in this condition, though?

**Comment by imbstack** [comment]
I don't see any tests saying they're being skipped. It's possible (likely?) that some just aren't really doing anything without creds I suppose. I can try to look through and verify.

**Comment by djmitche** [comment]
Oh, I'm thinking of hooks.  Yes, this works without credentials.

**Pull request merged**
